[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/studio/*"
  to = "/studio/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 